### PR TITLE
Node 10 support

### PR DESCRIPTION
**Pull request by thesocialdev**
1) Forking third-party packages to use @kartotherian/mapnik
2) Make new packages comply with the new package name
3) Remove package-lock.json files that make the build fail
4) Add support for docker configuration file
5) Tested against node v10.14.2

Bug: [T215523](https://phabricator.wikimedia.org/T215523)

### CODE REVIEW

**Comment by mdholloway** [comment]
Nice.  This works well on my local machine.

I wonder if there's a way to do it without having to fork and import all of this additional stuff.  I haven't come up with anything...

I also wonder if this should be a separate 'wikimedia' branch or something, rather than going into master, since it's really a workaround specific to our situation. I guess it depends how much usage this project is getting outside Wikimedia.

**Comment by nyurik** [comment]
yeah, I am not a big fan of merging the mapnik github either -- it makes download much bigger, and it will go away soonish (I hope).  Lets figure out a way to keep forked repos separatelly. Afterall , there is always a hope that we will defork it sooner or later.

**Comment by thesocialdev** [comment]
@nyurik and @mdholloway I cleaned the repository, kept the new forked repositories out of the monorepo project. I published alpha versions of these changes so I can test packaging and deploy. How should we proceed? I see two options:

1) Merge to master
2) Have a separate branch named 'wikimedia'

What do you think?

**Comment by thesocialdev** [comment]
@nyurik and @mdholloway I'm going to be bold and make a Wikimedia branch for this code, this way we can have more time to evaluate if the changes fit the kartotherian roadmap. Also, I'll be publishing the code as an alpha version to not mess with the versioning of the project, although [it is ready for production](https://phabricator.wikimedia.org/T215523#5151185). Let me know if you have any concerns and/or questions.

**Comment by mdholloway** [comment]
:+1:

**Comment by nyurik** [comment]
:+1: separate branch makes good sense until I finalize with all the other projects so to not block. Thanks for moving forward :)

**Comment by nyurik** [comment]
P.S. Is node10 branch still needed?

**Comment by thesocialdev** [comment]
> P.S. Is node10 branch still needed?

Good catch. Thanks!

**Pull request merged**
