### PR TITLE
Move changes from geoshapes/pull/6

### PR DESCRIPTION
**Pull request by thesocialdev**
1) Split geoshapes.js into index.js, lib/geoshape.js, and queries.yaml
2) Separate Geoshapes logic from service configuration
3) Load queries through .yaml file to make code cleaner
4) Brake index.js into several function to explicitly call step by step
and improve code clarity
5) Clean unnecessary code
6) Adding eslint and fixing linter errors
7) ignore travis.yml change since the monorepo won't be configured for
travis
8) Add mocha for future testing scripts

Former PR at https://github.com/kartotherian/geoshapes/pull/6

### CODE REVIEW

**Review by nyurik — APPROVED** [review]
lgtm!  Just keep in mind that I have made significant progress on this sub-project in https://github.com/Sophox/sophox/blob/master/osm-regions-server/server.js -- essentially it returns far cleaner results (without gaps, and much smaller) because it performs geoshape optimizations as a single operation -- e.g. if you have multiple regions, they are optimized together, thus it doesn't create any region misallignments / overlaps / gaps.

**Comment by thesocialdev** [comment]
> lgtm! Just keep in mind that I have made significant progress on this sub-project in https://github.com/Sophox/sophox/blob/master/osm-regions-server/server.js -- essentially it returns far cleaner results (without gaps, and much smaller) because it performs geoshape optimizations as a single operation -- e.g. if you have multiple regions, they are optimized together, thus it doesn't create any region misallignments / overlaps / gaps.

That sounds good, what do you think about creating a PR with those changes here?

**Comment by nyurik** [comment]
Heh, its on my todo list :)
I need to get Tilerator into a good shape to use the latest openmaptiles `AsMVT` methods first.

**Comment by thesocialdev** [comment]
> Heh, its on my todo list :)
> I need to get Tilerator into a good shape to use the latest openmaptiles `AsMVT` methods first.

Can we have this todo/road-map shared and documented somewhere? I think it would be good to have it, I have some thoughts too that I would like to share.

**Comment by nyurik** [comment]
Sure, I think the best way is to add them as issues, and tag them as "feature requests" ?     We could use a project too, but i think issues are much simpler and straightforward.

**Pull request merged**
