### PR TITLE
point to latest master version of kartotherian/snapshot

### PR DESCRIPTION
**Pull request by gehel**

### CODE REVIEW

**Comment by nyurik** [comment]
@gehel, let's publish an updated kartotherian/snapshot, instead of using unversioned links.

**Comment by gehel** [comment]
@nyurik that's definitely the goal! We're iterating to fix broken dependencies with @pnorman, we'll fix all versions once we have something working.

Note: we should probably do that in a branch and merge it once all problems are resolved, you're right... sorry for the noise!

**Comment by nyurik** [comment]
@gehel no worries.  Do you want to close this PR for now?

**Comment by pnorman** [comment]
This is being superseded by the collab team work to get all the versions working together again.

**Pull request closed without merging**
