### PR TITLE
Migrate to monorepo / yarn

### PR DESCRIPTION
**Pull request by nyurik**
* Merges all relevant repos except for the style ones into a single mono-repo, using merge commits
* Uses `yarn` [workspaces](https://yarnpkg.com/lang/en/docs/workspaces/)
* Installation is as simple as running `yarn` from root

### CODE REVIEW

**Review by nickpeihl — APPROVED** [review]
lgtm 

Running `yarn` in root worked perfectly. 👍

**Comment by MaxSem** [comment]
Can this be merged? On a side note, there's kartotherian/babel#23.

**Comment by nyurik** [comment]
@MaxSem almost - I actually need to make a few changes to the package.json scripts and documentation - running things now require slightly different paths.  Should be ready within a few days.

**Comment by nyurik** [comment]
P.S. @MaxSem I saw it -- that patch needs fixing first, it doesn't go through the tests (which also reminds me that we should get all tests running here before merging)

**Comment by thesocialdev** [comment]
@nyurik the service-runner packaging build only supports npm. We should find a workaround for that (maybe keep lerna). It is not desirable to change build to, the Docker build process is important on the deployment pipeline.

**Review by thesocialdev — CHANGES_REQUESTED** [review]
Yarn is not supported for the service build in the deployment pipeline.

**Comment by nyurik** [comment]
@mateusbs17 what command do you run with the service-runner to build the package?  Is there a build process documentation? We would still keep `lerna` - regardless of npm vs yarn, but in the yarn's case it will be far safer, as yarn knows package management internals/linking/dependencies much better than lerna would.

Now come to think of it, I don't actually think build process has anything to do with npm vs yarn here.  The build process would not (and should not) run from the root.  Instead, it should go to the `/packages/kartotherian` dir, and run `npm install` from there.  The only issue is that there will be two different lock files - `yarn.lock` in the root, and npm's `packages-lock.yaml` in kartotherian dir.  Not ideal, but shouldn't be too big of a concern.

**Comment by thesocialdev** [comment]
> @mateusbs17 what command do you run with the service-runner to build the package? 

That's the output I got. The script doesn't understand yarn's `package.json`. I am pinging @d00rman to ask for a little more context on that, maybe I am doing it wrong.
```
$ > ./server.js docker-test

Sending build context to Docker daemon  34.82kB
Step 1/15 : FROM debian:stretch
 ---> de8b49d4b0b3
Step 2/15 : RUN apt-get update && apt-get install -y nodejs nodejs-legacy git wget build-essential python fonts-dejavu libboost-filesystem-dev libboost-regex-dev libboost-system-dev libcairo2-dev libfreetype6-dev libgdal-dev libharfbuzz-dev libjpeg-dev libpng-dev libpq-dev libproj-dev libtiff-dev libwebp-dev libxml2-dev libmapbox-variant-dev libboost-program-options-dev libboost-thread-dev apt-transport-https && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 6ab97863066e
Step 3/15 : RUN echo > /etc/apt/sources.list && echo deb "https://apt.wikimedia.org/wikimedia stretch-wikimedia main" >> /etc/apt/sources.list
 ---> Using cache
 ---> 6794486754a5
Step 4/15 : RUN apt-get update && apt-get install -y --force-yes -t stretch-wikimedia libmapnik-dev libmapnik3.0 && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 87264dfd991b
Step 5/15 : ENV NVM_DIR /usr/local/nvm
 ---> Using cache
 ---> 10065eeac5bf
Step 6/15 : RUN wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash && . $NVM_DIR/nvm.sh && nvm install 6.11.1
 ---> Using cache
 ---> 331655d7f705
Step 7/15 : RUN mkdir /opt/service
 ---> Running in c3773112b560
Removing intermediate container c3773112b560
 ---> aa519b9fd0b3
Step 8/15 : ADD . /opt/service
 ---> ada934946116
Step 9/15 : WORKDIR /opt/service
 ---> Running in 7416e8d4cd9e
Removing intermediate container 7416e8d4cd9e
 ---> 48d519648e47
Step 10/15 : RUN . $NVM_DIR/nvm.sh && nvm use 6.11.1 && npm install && npm dedupe
 ---> Running in c63a04b4ceac
Now using node v6.11.1 (npm v3.10.10)
npm ERR! addLocal Could not install /tmp/npm-237-76253637/git-cache-55f0be7d/5f891becafd04b30fd6b5f12980f6c21813bb33e
npm ERR! Linux 4.9.0-8-amd64
npm ERR! argv "/usr/local/nvm/versions/node/v6.11.1/bin/node" "/usr/local/nvm/versions/node/v6.11.1/bin/npm" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! No version provided in package.json
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/service/npm-debug.log
The command '/bin/sh -c . $NVM_DIR/nvm.sh && nvm use 6.11.1 && npm install && npm dedupe' returned a non-zero code: 1
ERROR: Could not build the docker image!
ERROR: docker build exited with code 1
```

**Comment by nyurik** [comment]
@mateusbs17 please clarify 1) which repository you ran it from, and 2) the directory from which you ran that. Thanks!

**Comment by nyurik** [comment]
@mateusbs17 I think you had your package.json misconfigured. 

In your `maps/kartotherian/package` repo, change `package.json` to depend on `"kartotherian": "1.1.0-alpha",` instead of depending on the github master branch.  The `1.1.0-alpha` is the version I published directly from the packages.

My steps so far (on Ubuntu 18.04, node 8.13.0, npm 6.7.0):
```bash
mkdir tmp && cd tmp   ## clean dir
git clone https://gerrit.wikimedia.org/r/maps/kartotherian/package --recurse-submodules
git clone https://gerrit.wikimedia.org/r/maps/kartotherian/deploy --recurse-submodules

cd package
git config deploy.dir "$(dirname "$(pwd)")/deploy"   ## Stores deploy dir
git config deploy.name kartotherian

## This step is clearly wrong, but there is no config.yaml in the package dir, and the build script seems to require it...?
## I used the config.dev.yaml from the main kartotherian repo
curl https://raw.githubusercontent.com/kartotherian/kartotherian/master/config.dev.yaml > config.yaml

npm install service-runner

./server.js build --deploy-repo
```

**Review by thesocialdev — APPROVED** [review]

**Comment by nyurik** [comment]
DONE, thanks everyone!  I will make the other repos readonly

**Comment by thesocialdev** [comment]
For posteriority, publishing the kartotherian package on npm and setting the dependency with the right version at the package repo was tested and works just fine, this way service-runner never tries to build from the root of the repository.

**Pull request merged**
